server:
  port: 8083
  tomcat:
    connection-timeout: 18000000
  servlet:
    session:
      timeout: 30m #建议30分钟，时间太短会不准

spring:
  application:
    name: hogwarts-mini  #微服务名称，如果是单个服务就无所谓，spring-cloud集群中是个很重要的标识


hogwarts:
  key: "Hogwarts"